---
# tasks file for 2do_parcial

- debug:
    msg: "Tareas del 2do Parcial"

- name: Crear carpeta de alumno
  file:
    path: /tmp/2do_parcial/alumno
    state: directory
    mode: '0755'

- name: Crear carpeta de equipo
  file:
    path: /tmp/2do_parcial/equipo
    state: directory
    mode: '0755'

- name: Generar datos del alumno
  template:
    src: datos_alumno.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt

- name: Generar datos del equipo
  template:
    src: datos_equipo.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt

- name: Habilitar sudo sin password para grupo 2PSupervisores
  become: yes
  copy:
    content: "%2PSupervisores ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/2PSupervisores
    owner: root
    group: root
    mode: '0440'
